/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_CHAT_PB_H_INCLUDED
#define PB_CHAT_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _ChatMsg {
    uint32_t seq;
    char from[16];
    char text[64];
    bool has_ack;
    bool ack;
} ChatMsg;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define ChatMsg_init_default                     {0, "", "", false, false}
#define ChatMsg_init_zero                        {0, "", "", false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define ChatMsg_seq_tag                          1
#define ChatMsg_from_tag                         2
#define ChatMsg_text_tag                         3
#define ChatMsg_ack_tag                          4

/* Struct field encoding specification for nanopb */
#define ChatMsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   seq,               1) \
X(a, STATIC,   REQUIRED, STRING,   from,              2) \
X(a, STATIC,   REQUIRED, STRING,   text,              3) \
X(a, STATIC,   OPTIONAL, BOOL,     ack,               4)
#define ChatMsg_CALLBACK NULL
#define ChatMsg_DEFAULT (const pb_byte_t*)"\x20\x00\x00"

extern const pb_msgdesc_t ChatMsg_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ChatMsg_fields &ChatMsg_msg

/* Maximum encoded size of messages (where known) */
#define CHAT_PB_H_MAX_SIZE                       ChatMsg_size
#define ChatMsg_size                             90

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
